title: Divergences
subtitle: Feeling closer in different ways
description: > # this means to ignore newlines until "baseurl:"
  Working in different directions
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Romain Girard - romaingd # add your name
author-name: Romain Girard
author-img: profile-picture.jpg # add your photo
about-author: > # add description
  I currently work as a <strong> data scientist </strong> at Implicity,
  where I develop machine learning techniques to study strokes and heart failure.
  <br><br>
  I am strongly interested in both <strong>data science for healthcare</strong>
  and <strong>theoretical machine learning</strong>.
  <br><br>
  I graduated in 2018 from École polytechnique, Paris.
  <br><br> I hold a M.Sc. degree from the MVA <i>(Mathématiques, Vision,
  Apprentissage)</i> master at ENS Paris-Saclay,
  with an emphasis on machine learning and statistics.
# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: romaingd # add your Github handle
social-linkedin: romain-girard-4396ab11b/ # add your Linkedin handle
social-email: # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
# analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag        # Search Engine Optimization

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
