# basic options
title: Divergences
author: Romain Gd
email: your-email@domain.com
description: Working on a couple things
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
